version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            APP_ENV: production
            APP_DEBUG: 'false'

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: apka_oslava    # tohle musí odpovídat tomu, co máš v DB_DATABASE v .env
            MYSQL_ROOT_PASSWORD: 1717  # nastav bezpečné heslo
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    dbdata:
